server:
  port: 8080 #端口号
spring:
  application:
    name: reggie_take_out #默认工程名，应用的名称
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: 192.168.41.1
    port: 6379
    database: 0
mybatis-plus:
  configuration:
    #address_book-->AddressBook
    #user_name-->userName
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #驼峰命名法
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\img11111111111\